name: dicom_viewer
description: A Flutter DICOM viewer app with gradient chest x-ray home background and black viewer window.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  http: ^1.2.1
  path: ^1.8.3
  path_provider: ^2.1.2

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/chest_xray.jpg